name: Docker PR Build

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.repository_owner }}/baxter

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      # Build base Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: base
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:base

      # Build VNC Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build VNC image
        uses: docker/build-push-action@v6
        with:
          context: vnc
          pull: false
          push: false
          tags: ${{ env.IMAGE_NAME }}:vnc
